spring:
  application:
    name: demo-dong\

  # Database Settings
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # Spring AI Settings
  ai:
    openai:
      api-key: ${GROQ_API_KEY}
      base-url: https://api.groq.com/openai
      model: llama-3.1-8b-instant
      max-tokens: 2048

# Logging Settings
logging:
  level:
    com.back.myboilerplate: DEBUG


server:
  port: 8090

naver:
  api:
    client-id : ${NAVER_CLIENT_ID}
    client-secret : ${NAVER_CLIENT_SECRET}
    news-url: https://openapi.naver.com/v1/search/news.json

stock:
  yahoo:
    rss-url: https://finance.yahoo.com/rss/headline?s=


telegram:
  bot_token : ${TELEGRAM_BOT_TOKEN}
  chat-id : ${TELEGRAM_CHAT_ID}
