spring:
  application:
    name: demo-dong\

  # Database Settings
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true

  # Spring AI Settings
  ai:
    openai:
      api-key: ${GROQ_API_KEY}
      base-url: https://api.groq.com/openai
      model: llama3-8b-8192
      max-tokens: 2048

# Logging Settings
logging:
  level:
    com.back.myboilerplate: DEBUG


server:
  port: 8090

naver:
  api:
    client-id : ${NAVER_CLIENT_ID}
    client-secret : ${NAVER_CLIENT_SECRET}
    news-url: https://openapi.naver.com/v1/search/news.json

stock:
  yahoo:
    rss-url: https://finance.yahoo.com/rss/headline?s=

